const curriculumData = [
    { day: 1, topic: "Installation, Variables & User Input", category: "basics", file: "Source Code/Day 1/Name.rb" },
    { day: 2, topic: "Methods and Conditional if-else", category: "basics", file: "Source Code/Day 2/If_Else_Statement.rb" },
    { day: 3, topic: "Classes and Objects", category: "basics", file: "Source Code/Day 3/Class_&_Object.rb" },
    { day: 4, topic: "Getter, Setter and to_s Method", category: "basics", file: "Source Code/Day 4/To_s_Method.rb" },
    { day: 5, topic: "Class Variable and Self Method", category: "basics", file: "Source Code/Day 5/Self_Keyword.rb" },
    { day: 6, topic: "Loops", category: "logic", file: "Source Code/Day 6/While_Loop.rb" },
    { day: 7, topic: "Break, Next and Redo Statement", category: "logic", file: "Source Code/Day 7/Break_Statement.rb" },
    { day: 8, topic: "Block and Yield", category: "logic", file: "Source Code/Day 8/Block_&_Yield.rb" },
    { day: 9, topic: "Module Concept with Class", category: "modular", file: "Source Code/Day 9/Module_Concept.rb" },
    { day: 10, topic: "Require & Include Statement", category: "modular", file: "Source Code/Day 10/Include_Statement.rb" },
    { day: 11, topic: "Array Basics", category: "modular", file: "Source Code/Day 11/Array_Basics.rb" },
    { day: 12, topic: "2D Arrays", category: "modular", file: "Source Code/Day 12/2D_Array.rb" },
    { day: 13, topic: "Hash", category: "modular", file: "Source Code/Day 13/Hash_Basics.rb" },
    { day: 14, topic: "Random Numbers and Menu Class", category: "modular", file: "Source Code/Day 14/Menu_Class.rb" },
    { day: 15, topic: "Inheritance", category: "advanced", file: "Source Code/Day 15/Inheritance.rb" },
    { day: 16, topic: "Operator Overloading", category: "advanced", file: "Source Code/Day 16/Operator_Overloading.rb" },
    { day: 17, topic: "Freezing Objects", category: "advanced", file: "Source Code/Day 17/Freeze_Object.rb" },
    { day: 18, topic: "Proc and Lambda", category: "advanced", file: "Source Code/Day 18/Proc_&_Lambda.rb" },
    { day: 19, topic: "Arity Method", category: "advanced", file: "Source Code/Day 19/Arity_Method.rb" },
    { day: 20, topic: "Date and Time", category: "advanced", file: "Source Code/Day 20/Date_Time.rb" },
    { day: 21, topic: "TicTacToe Game", category: "interactive", file: "Source Code/Day 21/TicTacToe/TicTacToe.rb" },
    { day: 22, topic: "Hangman Game", category: "interactive", file: "Source Code/Day 22/Hangman.rb" },
    { day: 23, topic: "Rails: Installation & Intro", category: "rails", file: "Source Code/Day 23-30/README.md" },
    { day: 24, topic: "Rails: Website Development", category: "rails", file: "Source Code/Day 23-30/README.md" },
    { day: 25, topic: "Rails: CRUD Database", category: "rails", file: "Source Code/Day 23-30/README.md" },
    { day: 26, topic: "Rails: Bootstrap Styling", category: "rails", file: "Source Code/Day 23-30/README.md" },
    { day: 27, topic: "Rails: Devise Auth", category: "rails", file: "Source Code/Day 23-30/README.md" },
    { day: 28, topic: "Rails: User Associations", category: "rails", file: "Source Code/Day 23-30/README.md" },
    { day: 29, topic: "Rails: List Styling", category: "rails", file: "Source Code/Day 23-30/README.md" },
    { day: 30, topic: "Rails: Cloud Deployment", category: "rails", file: "Source Code/Day 23-30/README.md" }
];
